blank_issues_enabled: false
contact_links:
 - name: GitHub Community Support
   url: https://github.com/virtual-tech-school/frytheweb/discussions
   about: Please ask and answer questions here
 - name: Discord Community Support
   url: https://discord.gg/EYB8tQxjxH
   about: Please ask and answer questions here
